name = "cloudflare-email-displayer"
main = "src/index.js"
compatibility_date = "2024-12-30"
compatibility_flags = [ "nodejs_compat" ]

# KV Namespace removed as per user request (Migrated to Railway)

[observability]
enabled = false